### PR TITLE
Fix numpy 2.3+ compatibility by using public APIs

### PR DESCRIPTION
**Pull request by dhalf**
Fix numpy 2.3+ compatibility in test_polyglot.py

  Problem

  The check_numpy() function in fickling/polyglot.py was failing with numpy 2.3.3+ due to an AttributeError: module 'numpy.lib.format' has no attribute '_header_size_info'.

  In numpy 2.0+, the internal structure was reorganized and the private _header_size_info variable was moved to numpy.lib._format_impl and is no longer re-exported from numpy.lib.format.

  Solution

  Replace the private API usage with numpy's public APIs:
  - read_array_header_1_0() for numpy format version 1.0
  - read_array_header_2_0() for numpy format versions 2.0 and 3.0

  Changes

  - Updated check_numpy() function in fickling/polyglot.py to use public APIs
  - Removed unused imports (ast and struct) that were only used in the old implementation
  - Added support for numpy format version 3.0
  - Improved error handling with explicit exception catching

  Benefits

  1. Future-proof: Uses stable, documented public APIs
  2. Backward compatible: Works with numpy >= 1.24.0 through 2.3.5+
  3. Cleaner code: Eliminates manual struct parsing and ast.literal_eval
  4. Achieves original goal: Avoids private API dependency (the original code acknowledged using a private variable)

  Testing

  All tests pass with numpy 2.3.5:
  - ✅ test_numpy_non_pickle - Detects regular numpy arrays
  - ✅ test_numpy_pickle - Detects numpy files with pickled objects
  - ✅ test_recursive_tar - Recursive detection in tar archives
  - ✅ test_recursive_zip - Recursive detection in zip archives
  - ✅ All other polyglot tests (12 passed, 1 skipped)

  Tested on: Python 3.13.7, pytest 9.0.1, numpy 2.3.5

  Closes

  Fixes issue with test_polyglot.py failing on numpy 2.3.3+

### CODE REVIEW

**Review by thomas-chauchefoin-tob — APPROVED** [review]
Just fixed the Ruff reports and reverted `uv.lock` changes, we'll bump dependencies in a separate PR. Thanks!
